publishDir = "public"
baseURL = "http://veikkola.greidi.net/"
languageCode = "fi-FI"
title = "Veikkolan kiipeilypuisto"
theme = "codex"

# Override these settings with your own
copyright = "© {year} Juuso Korhonen"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  # twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/juusokorhonen/veikkola"
  # email = "mailto:<your email>"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["GitHub"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "tietoa"
  title = "Tietoa"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blogi"
  title = "Blogi"
  url = "/blog"

[[menu.main]]
  identifier = "sectors"
  name = "sektorit"
  title = "Sektorit"
  url = "/sector"

[[menu.main]]
  identifier = "routes"
  name = "reitit"
  title = "Reitit"
  url = "/route"

# Custom taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  topo = "topos"
  sector = "sectors"
  type = "types"
  setter = "setters"
  
